FROM debian:12 

# Install Python, build tools, and curl
RUN apt update -y && apt upgrade -y && \
    apt install -y python3 python3.11-venv python3-pip build-essential curl

# Install the latest version of Rust and Cargo
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> /etc/profile && \
    echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> /etc/environment

# Ensure Rust and Cargo are available in the current shell
ENV PATH="/root/.cargo/bin:${PATH}"

# Verify Rust and Cargo installation TODO: Remove this line in production
RUN rustc --version && cargo --version

# Set the working directory
WORKDIR /NeuralNetwork

# Create and use a virtual environment
RUN python3 -m venv env
RUN ./env/bin/pip install --upgrade pip

# Install dependencies in the virtual environment
COPY requirements.txt ./
RUN ./env/bin/pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY data ./data
COPY . .

ENV SCRIPT_NAME=training/training_pipe.py


# Set the entry point
ENTRYPOINT ["sh", "-c", "./env/bin/python $SCRIPT_NAME"]

#RUN CMD
# docker run -e SCRIPT_NAME=ScriptNameFromRoot -v C:folder/in/host:/folder/in/project model-data-maker  
# docker run -e SCRIPT_NAME=training/train_spacy_ner.py -v C:\Users\NicoD\OneDrive\Desktop\temp:/NeuralNetwork/output_data model-data-maker  