services:
  api:
    build: .
    platform: linux/amd64   
    container_name: interview-coach-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./NeuralNetwork/data:/server/NeuralNetwork/data
      - ./NeuralNetwork/models:/server/NeuralNetwork/models #map host system to container

  db:
    image: mysql:8.0        
    container_name: interview-coach-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: interview_coach
      MYSQL_USER: coach_user
      MYSQL_PASSWORD: coach_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # create a folder in volumes for safe keeping

volumes:
  mysql_data: