FROM python:3

# Set the working directory
WORKDIR /server

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

# Allow passing arguments correctly
ENTRYPOINT ["python", "index.py"]

#to run
# docker run -v .../server/output:/server/output -p 5000:5000 image-name