FROM python:3

# Set the working directory
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENTRYPOINT ["python", "index.py"]
CMD ["--filepath", "/app/output.txt"]

# try 
# docker run -p 5000:5000 -v C:/Users/NicoD/Downloads:/app/output scraper-server-ic --filepath /app/output/output.txt